base_url = "https://getchoo.com"

title = "getchoo's website"
description = "guzzle guzzle"
minify_html = true
hard_link_static = true

[markdown]
highlight_code = false
render-emoji = true
external_links_target_blank = true
lazy_async_image = true

[extra]
gifs = [
	{ name = "acab.gif", alt = "ACAB!" },
	{ name = "arnold.gif", alt = "Hey Arnold!" },
	{ name = "capitalism.gif", alt = "Let's crush capitalism!" },
	{ name = "legalize.gif", alt = "Legalize marijuana now!" },
	{ name = "poweredbynix.svg", alt = "Powered by NixOS", href = "https://github.com/sakecode" },
	{ name = "pride.gif", alt = "LGBTQ Pride now!" },
	{ name = "steam.gif", alt = "Play on Steam!", href ="https://dnsense.pub/" },
	{ name = "weezer.gif", alt = "Weezer fan" },
]

nav_links = [
	{ name = "home", url = "/" },
	{ name = "github", url = "https://github.com/getchoo" }
]

repository_url = "https://github.com/getchoo/website"
