name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: 20

jobs:
  ci:
    strategy:
      matrix:
        include:
          - name: Build
            command: build
          - name: Check
            command: ci

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install package manager
        run: |
          corepack enable
          corepack prepare --activate

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Run ${{ matrix.command }}
        run: |
          pnpm run ${{ matrix.command }}
