name: deploy to gh pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install Nix
        uses: cachix/install-nix-action@v20

      - name: build site
        run: |
          nix shell nixpkgs#{bash,nodejs,nodePackages.yarn} \
            --command bash -c 'yarn install -D && yarn build'

      - name: setup pages
        uses: actions/configure-pages@v3

      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "dist"

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1
