name: Nix

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check flake
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Setup cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Run check
        run: |
          nix flake check -L --show-trace
